### PR TITLE
Build with Qt6

### PR DESCRIPTION
**Pull request by DaPigGuy**

### CODE REVIEW

**Comment by guihkx** [comment]
Isn't this a bit early, though?

I think KDE's Breeze theme isn't even supported in Qt 6 yet, so running this build on my Plasma 5 desktop makes Prism look out of place, since the default Qt theme (Fusion) is used instead.

In my opinion, the migration to the Qt 6 runtime should be held until Plasma 6.0 is actually released. Unless the Qt 5 build of Prism lacks crucial features...?

**Comment by Scrumplex** [comment]
We could maybe offer this using Flathub Beta for users that might want Qt 6

**Comment by guihkx** [comment]
That sounds much better, in my opinion.

Btw, @DaPigGuy: Any particular reason you chose version 6.4 of the runtime (instead of 6.5)?

**Comment by DaPigGuy** [comment]
Had not realized there was now a 6.5 runtime :sweat_smile:

**Comment by Scrumplex** [comment]
I have created a beta branch for flathub beta.

**Pull request merged**
