### PR TITLE
Use fallback-x11

### PR DESCRIPTION
**Pull request by Scrumplex**
See https://github.com/PrismLauncher/PrismLauncher/pull/1744

### CODE REVIEW

**Comment by Scrumplex** [comment]
This won't work. This won't mount the X11 socket, on Wayland sessions. The launcher will work fine, the game won't.

**Comment by Trial97** [comment]
why the game won't work(I know nothing about flatpack)?
Better question do you know an alternative?

**Comment by Scrumplex** [comment]
The game won't work, as it doesn't support Wayland natively. Setting this to `fallback-x11` will apparently only mount the X11 socket if there is no Wayland socket. So Wayland users will be able to start the launcher, but the game will crash as there won't be an X11 socket

**Comment by Trial97** [comment]
Ok fell free to close both the PR and the issue then

**Pull request closed without merging**
